package evidence

import "testing"

// mr-r3y: freeform evidence fails closed — any "failed", and the shapes tools print, count as a failure — except the
// word "fail" in prose and reports that nothing failed. Before the fix, "the new tests fail against origin/main" (the
// tests CATCH the regression) marked passing evidence exit 1; the first cut of the fix narrowed "failed" and let real
// failure output through (#-review), so the default stays closed.
func TestFreeformFailureReadsFailuresNotTheWordFail(t *testing.T) {
	const passing = "go test ./... exited 0\n"
	for name, tc := range map[string]struct {
		text string
		want int
	}{
		// not failures: the word "fail" in prose, and a bounded clause reporting that nothing failed
		"the regression tests fail on the old code": {passing + "- the new tests fail against origin/main and pass here", 0},
		"fails, failing, failure mode":              {passing + "- covers the failure mode where the gate fails open; a failing case is pinned", 0},
		"a Fail-safe":                               {passing + "- the Fail-safe path is exercised", 0},
		"zero failed":                               {passing + "Tests: 12 passed, 0 failed", 0},
		"no tests failed":                           {passing + "no tests failed", 0},
		"0 tests failed.":                           {passing + "0 tests failed.", 0},
		"none of the checks failed":                 {passing + "none of the checks failed", 0},
		"0 of 10 failed":                            {passing + "0 of 10 failed", 0},
		"0/10 failed":                               {passing + "0/10 failed", 0},
		"Failures: 0, Errors: 0":                    {passing + "Tests run: 5, Failures: 0, Errors: 0", 0},
		"0 failing, 0 errors":                       {passing + "12 passing, 0 failing, 0 errors", 0},
		"0 failed in 1s":                            {passing + "5 passed, 0 failed in 1.2s", 0},
		"0 failed (cached)":                         {passing + "5 passed, 0 failed (cached)", 0},
		"dotnet all passed":                         {passing + "Passed!  - Failed: 0, Passed: 5", 0},
		"ansible failed=0":                          {passing + "ok=5 changed=0 failed=0", 0},
		"CRLF zero":                                 {passing + "Tests: 3 passed, 0 failed\r\nexit 0 ok", 0},
		"error cases in prose":                      {passing + "- covers 2 error paths; added 2 error cases", 0},
		"fail2ban":                                  {passing + "- fail2ban config untouched", 0},
		"a test named should fail":                  {"✓ should fail (3 ms)\nTests: 5 passed, 5 total", 0},
		"a go subtest named fail":                   {"--- PASS: TestX/fail (0.00s)\nPASS\nok  \tpkg\t0.1s", 0},
		"ansible recap":                             {passing + "ok=5 changed=0 unreachable=0 failed=0 skipped=0", 0},
		"node test fail 0":                          {passing + "# tests 5\n# pass 5\n# fail 0\n# cancelled 0", 0},
		"node test info fail 0":                     {passing + "ℹ pass 5\nℹ fail 0", 0},
		"bun 0 fail":                                {passing + " 5 pass\n 0 fail\nRan 5 tests", 0},
		"ctest":                                     {passing + "100% tests passed, 0 tests failed out of 5", 0},
		"a release candidate":                       {passing + "- verified on v0.14.0-rc1", 0},
		"coloured pass":                             {"\x1b[32mok\x1b[0m  \tpkg\t0.1s", 0},
		"a go subtest run named fail":               {"=== RUN   TestX/fail\n--- PASS: TestX/fail (0.00s)\nPASS\nok  \tpkg\t0.1s", 0},
		"a test file named fail":                    {passing + "✓ src/fail.test.ts (3 tests)", 0},
		"doesn't fail":                              {passing + "- the retry path doesn't fail anymore", 0},
		"fail without the fix":                      {passing + "- the new tests fail without the fix", 0},
		"expected to fail":                          {passing + "- TestBadInput is expected to fail on malformed input", 0},

		"unittest expected failures": {passing + "Ran 5 tests in 0.01s\n\nOK (skipped=1, expected failures=1)", 0},
		// failures: any "failed", the shapes tools print, and a zero that sits beside a real count
		"go test FAIL line":           {"ok  \tgithub.com/a\t0.1s\nFAIL\tgithub.com/b\t0.2s", 1},
		"go test --- FAIL":            {passing + "--- FAIL: TestY (0.00s)", 1},
		"pytest FAILED":               {passing + "FAILED tests/test_x.py::test_y - assert 1 == 2", 1},
		"a failure count":             {passing + "=== 2 failed, 10 passed in 0.3s ===", 1},
		"jest summary":                {passing + "Tests:       1 failed, 3 passed, 4 total", 1},
		"junit failures":              {passing + "Tests run: 5, Failures: 1, Errors: 0", 1},
		"maven errors":                {passing + "Tests run: 5, Failures: 0, Errors: 1", 1},
		"BUILD FAILURE":               {passing + "[INFO] BUILD FAILURE", 1},
		"FAILURES!":                   {passing + "FAILURES!", 1},
		"dotnet":                      {passing + "Failed!  - Failed: 1, Passed: 5", 1},
		"label then count":            {passing + "Passed: 0 Failed: 3", 1},
		"zero passed then failed":     {passing + "0 passed 3 failed", 1},
		"zero skipped then failed":    {passing + "Tests: 0 skipped 3 failed", 1},
		"zero failed then failed":     {passing + "Tests: 0 failed 1 failed", 1},
		"a version before failed":     {passing + "go 1.0 failed", 1},
		"exited 0 build failed":       {"exited 0 build failed", 1},
		"test(s) failed":              {passing + "3 test(s) failed", 1},
		"go vet failed":               {passing + "go vet failed", 1},
		"failed to compile":           {passing + "Failed to compile.", 1},
		"command failed":              {passing + "Command failed.", 1},
		"a test that failed":          {passing + "TestFoo failed", 1},
		"no tests ran, one failed":    {passing + "no tests skipped; 1 failed", 1},
		"a zero beside a real one":    {passing + "0 failed in unit, 2 failed in integration", 1},
		"mocha failing":               {passing + "3 passing\n1 failing", 1},
		"tests failing":               {passing + "2 tests failing", 1},
		"rspec failure":               {passing + "10 examples, 1 failure", 1},
		"node test fail":              {passing + "# tests 5\n# pass 4\n# fail 1", 1},
		"node test info fail":         {passing + "ℹ fail 1", 1},
		"bun fail":                    {passing + "5 pass\n1 fail", 1},
		"TAP not ok":                  {passing + "ok 1 - a\nnot ok 2 - b", 1},
		"make Error":                  {passing + "make: *** [test] Error 2", 1},
		"tsc":                         {passing + "src/a.ts(1,1): error TS2322: Type 'x' is not assignable", 1},
		"msbuild":                     {passing + "Program.cs(3,1): error CS1002: ; expected", 1},
		"npm ERR":                     {passing + "npm ERR! code 1", 1},
		"exit status":                 {passing + "exit status 1", 1},
		"a nonzero exit":              {passing + "golangci-lint run ./... exited 1", 1},
		"an error line":               {passing + "error: cannot find package", 1},
		"a failure with no success":   {"FAIL\tgithub.com/b\t0.2s", 1},
		"no success signal":           {"I looked at it", 1},
		"a failure beats a success":   {"tests passed\nlint failed", 1},
		"only the success, no report": {passing, 0},
		"Fail because":                {passing + "Status: Fail because timeout", 1},
		"Fail - flaky":                {passing + "Fail - flaky", 1},
		"Fail (expected)":             {passing + "Fail (expected)", 1},
		"lint: fail (3 warnings)":     {passing + "lint: fail (3 warnings)", 1},
		"fail - see log":              {passing + "Result: fail - see log", 1},
		"build fail (exit)":           {passing + "build fail (exit)", 1},
		"fail / see below":            {passing + "tests: fail / see below", 1},
		"Fail/timeout":                {passing + "build: Fail/timeout", 1},
		"RESULT: Fail foo":            {passing + "RESULT: Fail foo", 1},
		"fail - 3 tests broke":        {passing + "fail - 3 tests broke", 1},
		"error: 0":                    {passing + "error: 0", 1},
		"Fail with problems":          {passing + "Result: Fail with 3 problems", 1},
		"Fail a file":                 {passing + "Fail foo.test.ts", 1},
		"FAIL 0":                      {passing + "FAIL 0", 1},
		"wrapped exit code":           {passing + "exit code\n1", 1},
		"fail (see log)":              {"tests ok\nfail (see log)", 1},
		"fail - reason":               {"tests ok\nsmoke test: fail - timeout", 1},
		"result: fail some":           {"tests ok\nresult: fail some", 1},
		"wrapped exit":                {"go test ok\nexit\n1", 1},
		"lint: fail on files":         {passing + "lint: fail on 3 files", 1},
		"FAIL on windows":             {passing + "FAIL on windows", 1},
		"build FAIL when":             {passing + "build FAIL when tests broken", 1},
		"Status: fail on windows":     {passing + "Status: fail on windows", 1},
		"did fail":                    {"tests passed\nthe build did fail earlier", 1},
		"does fail on CI":             {"tests passed\nThe suite does fail on CI", 1},
		"Tests fail on CI":            {"tests passed\nTests fail on CI", 1},
		"FAIL under load":             {passing + "coverage FAIL under 80%", 1},
		"FAIL without cache":          {passing + "lint FAIL without flags", 1},
		"did fail to apply":           {"ok\nmigration did fail to apply", 1},
		"did fail against":            {"tests passed\nthe deploy did fail against staging", 1},
		"build-fail":                  {"ok\nbuild-fail", 1},
		"step-fail":                   {"ok\nci: unit-tests-fail", 1},
		"result.fail":                 {"ok\nresult.fail", 1},
		"unittest real failures":      {passing + "Ran 5 tests in 0.01s\n\nFAILED (failures=1, expected failures=1)", 1},
		"cannot fail is prose":        {passing + "- this path cannot fail", 0},
		"never fail is prose":         {passing + "- retries never fail silently", 0},
		"must fail is prose":          {passing + "- the negative case must fail", 0},

		"continues to fail":         {"go test ./... ok\nthe integration test continues to fail", 1},
		"started to fail":           {"tests passed; TestX started to fail", 1},
		"still fail before timeout": {"tests passed\nthey still fail before 5s timeout", 1},

		"Build failed 0":           {"ok\nBuild failed 0", 1},
		"FAILED 0":                 {"ok\nFAILED 0", 1},
		"jest FAIL before.test.js": {passing + "FAIL  before.test.js", 1},
		"will FAIL":                {passing + "the build will FAIL", 1},
		"FAIL against baseline":    {passing + "FAIL against baseline", 1},

		"a counted fail":             {passing + "3 tests fail and 9 pass", 1},
		"a counted fail in parens":   {passing + "Tests: 3 fail (of 10)", 1},
		"one test fails":             {passing + "1 test fails", 1},
		"two tests fail on windows":  {passing + "the 2 tests fail on windows", 1},
		"a fail verdict with a stop": {passing + "Result: Fail.", 1},

		"pytest error summary":        {passing + "=========== 5 passed, 1 error in 0.52s ===========", 1},
		"pytest error during":         {passing + "!!! Interrupted: 1 error during collection !!!", 1},
		"pytest ERROR line":           {passing + "ERROR tests/test_a.py - ImportError", 1},
		"mypy":                        {passing + "Found 2 errors in 1 file (checked 3 source files)", 1},
		"clang":                       {passing + "1 error generated.", 1},
		"rustc":                       {passing + "error[E0308]: mismatched types", 1},
		"segfault":                    {passing + "Segmentation fault (core dumped)", 1},
		"killed":                      {passing + "Killed", 1},
		"traceback":                   {passing + "Traceback (most recent call last):", 1},
		"negative exit":               {passing + "exit code: -1", 1},
		"rc=1":                        {passing + "rc=1", 1},
		"an error starting with 0":    {passing + "Error: 0 is not a valid port", 1},
		"zero label then errors":      {passing + "tests ok: failed=0 errors=3", 1},
		"failures=0 errors=1":         {passing + "failures=0 errors=1 skipped=2", 1},
		"Failures: 0 exit=1":          {passing + "Failures: 0 exit=1", 1},
		"coloured FAIL":               {"ok  \tgithub.com/a\t0.1s\n\x1b[31mFAIL\x1b[0m\tpkg 0.1s", 1},
		"coloured failed":             {passing + "\x1b[31mfailed\x1b[0m", 1},
		"colon-separated colour FAIL": {passing + "\x1b[38:2:255:0:0mFAIL\x1b[0m", 1},
		"counted modal is prose":      {passing + "1 should fail on origin/main without the fix", 0},
		"counted fail still counts":   {passing + "3 tests fail on origin/main", 1},
		"indented not ok":             {passing + "    not ok 2 - foo", 1},
		"exited with 1":               {passing + "npm test exited with 1", 1},
		"exit code was 1":             {"go test ./... exit code was 1; 5 tests passed", 1},
		"TypeError":                   {passing + "TypeError: x is not a function", 1},
		"AssertionError":              {passing + "AssertionError [ERR_ASSERTION]: expected 1 to equal 2", 1},
		"java exception":              {passing + `Exception in thread "main" java.lang.NullPointerException`, 1},
		"rust panic":                  {"test result: ok\nthread 'main' panicked at src/lib.rs:3:5:", 1},
		"errors and warnings":         {passing + "2 errors and 1 warning; tsc build passed", 1},
		"go build diagnostic":         {"ok  \tpkg\t0.1s\n# pkg\n./main.go:5:2: undefined: foo", 1},
		"golangci-lint issues":        {"ok  \tpkg\t0.1s\nmain.go:12:5: Error return value is not checked (errcheck)\n1 issues:", 1},

		"a fail verdict":         {passing + "Result: Fail", 1},
		"a lower-case status":    {passing + `{"status":"fail"}`, 1},
		"build fail at line end": {passing + "build fail", 1},
		"shard 0 failed":         {passing + "shard 0 failed", 1},
		"worker 0 failed.":       {passing + "worker 0 failed.", 1},
		"exit code 0 failed":     {"tests passed\nexit code 0 failed", 1},
		"exit code: 2":           {passing + "exit code: 2", 1},
		"exited with code":       {passing + "Process exited with code 1", 1},
		"exit=1":                 {passing + "exit=1", 1},
		"return code":            {passing + "return code: 3", 1},
		"found errors":           {passing + "Found 2 errors.", 1},

		// mr-b08: anchored tool-output shapes the reader did not recognize. Each is pinned to the START of a
		// line in a fixed format, so prose that merely names the phrase must NOT trip it (the prose cases below).
		"go panic":                   {passing + "panic: send on closed channel", 1},
		"go data race":               {"ok  \tpkg\t0.1s\nWARNING: DATA RACE", 1},
		"aborted core dumped":        {passing + "Aborted (core dumped)", 1},
		"make no rule":               {passing + "make: *** No rule to make target 'test'.  Stop.", 1},
		"git fatal":                  {passing + "fatal: not a git repository (or any parent up to mount point /x)", 1},
		"bash command not found":     {passing + "bash: pytest: command not found", 1},
		"zsh command not found":      {passing + "zsh: command not found: pytest", 1},
		"zsh colon not found":        {passing + "zsh:1: command not found: pytest", 1},
		"dash not found":             {passing + "sh: 1: pytest: not found", 1},
		"permission denied":          {passing + "bash: ./scripts/run.sh: Permission denied", 1},
		"permission denied crlf":     {passing + "bash: ./run.sh: Permission denied\r", 1},
		"bash script not found":      {passing + "bash: line 1: pytest: command not found", 1},
		"script permission denied":   {passing + "script.sh: line 3: /x/y: Permission denied", 1},
		"ssh permission denied":      {passing + "git@github.com: Permission denied (publickey).", 1},
		"zsh permission denied":      {passing + "zsh: permission denied: ./run.sh", 1},
		"dash permission denied":     {passing + "sh: 1: ./run.sh: Permission denied", 1},
		"login shell not found":      {passing + "-bash: pytest: command not found", 1},
		"aborted shell form":         {passing + "bash: line 1: 12345 Aborted (core dumped) ./prog", 1},
		"abort trap":                 {passing + "Abort trap: 6", 1},
		"aborted bare":               {passing + "Aborted", 1},
		"rubocop single file":        {passing + "1 file inspected, 1 offense detected", 1},
		"pytest no tests ran padded": {passing + "============================ no tests ran in 0.00s ============================", 1},
		"terminated by signal":       {passing + "Command terminated by signal 11", 1},
		"pytest no tests ran":        {passing + "no tests ran in 0.01s", 1},
		"jest no tests found code 1": {passing + "No tests found, exiting with code 1", 1},
		"jest coverage threshold":    {passing + `Jest: "global" coverage threshold for branches (80%) not met: 66%`, 1},
		"eslint warnings max 0":      {passing + "ESLint found too many warnings (maximum: 0).", 1},
		"eslint warnings max 10":     {passing + "too many warnings (maximum: 10)", 1},
		"prettier code style":        {passing + "[warn] Code style issues found in 2 files. Run Prettier with --write to fix.", 1},
		"black would reformat":       {passing + "would reformat src/a.py", 1},
		"rubocop offenses":           {passing + "5 files inspected, 3 offenses detected", 1},
		"rspec Failures header":      {passing + "Failures:", 1},
		"minitest Failure header":    {passing + "  1) Failure:", 1},
		"json exitCode fragment":     {passing + `"exitCode": 1`, 1},
		"json exitCode object":       {passing + `{"exitCode": 1}`, 1},

		// prose (or a PASSING tool line) naming the same words must NOT be read as a failure
		"prose: panic handling":    {passing + "- the state handles panic: by restarting", 0},
		"prose: permission denied": {passing + "- tests the Permission denied path", 0},
		"prose: no tests ran":      {passing + "- note: no tests ran in 0.00s was expected", 0},
		"prose: terminated signal": {passing + "- the worker handles terminated by signal cases", 0},
		"prose: offenses detected": {passing + "- a line with 5 files inspected, 3 offenses detected in prose", 0},
		// bare (unbulleted) prose naming a phrase must also stay passing - the anchors, not the '- ' prefix, do the work
		"prose bare not found":        {passing + "command not found handling is covered", 0},
		"prose bare denied":           {passing + "permission denied is handled by the sandbox", 0},
		"prose bare fatal":            {passing + "the fatal: handling is covered", 0},
		"prose bare no tests":         {passing + "no tests ran for the docs package", 0},
		"prose bare offenses":         {passing + "files inspected, 3 offenses detected", 0},
		"prose colon tag denied":      {passing + "Note: permission denied is exercised by the test", 0},
		"prose ssh denied":            {passing + "user@host: permission denied is covered", 0},
		"jest passWithNoTests code 0": {passing + "No tests found, exiting with code 0", 0},

		// the modal list (one source behind proseFail/modalFail) stays prose for every modal
		"modal would fail":  {passing + "- the check would fail without the fix", 0},
		"modal shall fail":  {passing + "- it shall fail loudly on bad input", 0},
		"modal can fail":    {passing + "- this path can fail on a bad socket", 0},
		"modal could fail":  {passing + "- the call could fail on a bad socket", 0},
		"modal will fail":   {passing + "- the retry will fail on a stale lock", 0},
		"modal may fail":    {passing + "- the call may fail on a timeout", 0},
		"modal might fail":  {passing + "- the retry might fail once", 0},
		"modal don't fail":  {passing + "- these steps don't fail on retry", 0},
		"modal didn't fail": {passing + "- the migration didn't fail", 0},
		"modal won't fail":  {passing + "- it won't fail on empty input", 0},

		// expectedFailures failing side: a real failure count beside a passing expected-failures count
		"failures beside expected": {passing + "Ran 5 tests\n\nfailures=1, expected failures=1", 1},
		"expected failures alone":  {passing + "Ran 5 tests\n\nOK (expected failures=2)", 0},
	} {
		tc := tc
		t.Run(name, func(t *testing.T) {
			bundle, err := Parse([]byte(tc.text))
			if err != nil {
				t.Fatalf("%v", err)
			}
			if got := bundle.Receipts[0].ExitCode; got != tc.want {
				t.Errorf("exit %d, want %d", got, tc.want)
			}
		})
	}
}
