package sourcereview

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func gitEnv() []string {
	return append(os.Environ(),
		"GIT_CONFIG_GLOBAL=/dev/null",
		"GIT_CONFIG_SYSTEM=/dev/null",
		"GIT_AUTHOR_NAME=Test",
		"GIT_AUTHOR_EMAIL=t@example.com",
		"GIT_COMMITTER_NAME=Test",
		"GIT_COMMITTER_EMAIL=t@example.com",
	)
}

func gitRun(t *testing.T, root string, args ...string) {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = root
	cmd.Env = gitEnv()
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
}

func newRepoBytes(t *testing.T, files map[string][]byte) (root, commit string) {
	t.Helper()
	root = t.TempDir()
	gitRun(t, root, "init", "-b", "main")
	gitRun(t, root, "config", "user.email", "t@example.com")
	gitRun(t, root, "config", "user.name", "Test")
	for p, body := range files {
		abs := filepath.Join(root, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(abs, body, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	gitRun(t, root, "add", "-A")
	gitRun(t, root, "commit", "-m", "fixture")
	cmd := exec.Command("git", "rev-parse", "HEAD")
	cmd.Dir = root
	cmd.Env = gitEnv()
	out, err := cmd.Output()
	if err != nil {
		t.Fatal(err)
	}
	return root, strings.TrimSpace(string(out))
}

func specFiles() map[string][]byte {
	return map[string][]byte{
		"pkg/app.go":      []byte("package pkg\n\nfunc App() int { return 1 }\n"),
		"pkg/note.go":     []byte("DO NOT EDIT\npackage pkg\n\nfunc Note() string { return \"n\" }\n"),
		"pkg/app_test.go": []byte("package pkg\n\nfunc TestApp(t *testing.T) {}\n"),
		"vendor/lib.go":   []byte("package vendor\n\nfunc Lib() {}\n// DROPME-vendor\n"),
		"go.sum":          []byte("example.com/mod v1.0.0 h1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa=\n"),
		"pkg/gen.go":      []byte("// Code generated by fixture. DO NOT EDIT.\npackage pkg\n\nfunc Gen() {}\n"),
		"pkg/blob.dat":    {0xff, 0xfe, 0x00, 0x01},
		"README.md":       []byte("# Demo\n\nDROPME-readme\n"),
		"config.yaml":     []byte("name: demo\nDROPME-config\n"),
	}
}

func droppedOnlyFiles() map[string][]byte {
	all := specFiles()
	delete(all, "pkg/app.go")
	delete(all, "pkg/note.go")
	return all
}

var specDropped = []string{
	"README.md",
	"config.yaml",
	"go.sum",
	"pkg/app_test.go",
	"pkg/blob.dat",
	"pkg/gen.go",
	"vendor/lib.go",
}
