package sourcereview

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestSelectSpecFixture(t *testing.T) {
	root, commit := newRepoBytes(t, specFiles())
	kept, dropped, gotCommit, err := Select(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if gotCommit != commit {
		t.Fatalf("commit %s want %s", gotCommit, commit)
	}
	var paths []string
	for _, f := range kept {
		paths = append(paths, f.Path)
		if !bytes.Equal(f.Body, specFiles()[f.Path]) {
			t.Fatalf("%s body = %q", f.Path, f.Body)
		}
	}
	if !reflect.DeepEqual(paths, []string{"pkg/app.go", "pkg/note.go"}) {
		t.Fatalf("kept %v", paths)
	}
	if !reflect.DeepEqual(dropped, specDropped) {
		t.Fatalf("dropped %v", dropped)
	}
}

func TestSelectDroppedOnlyFixture(t *testing.T) {
	root, _ := newRepoBytes(t, droppedOnlyFiles())
	kept, dropped, _, err := Select(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if len(kept) != 0 {
		t.Fatalf("kept %v", kept)
	}
	if !reflect.DeepEqual(dropped, specDropped) {
		t.Fatalf("dropped %v", dropped)
	}
}

func TestSelectEdges(t *testing.T) {
	files := map[string][]byte{
		"node_modules/x.go":    []byte("package x\n"),
		"third_party/y.go":     []byte("package y\n"),
		"internal/foo_test.go": []byte("package internal\n"),
		"fixtures/a.go":        []byte("package fixtures\nfunc A() {}\n"),
		"pkg/after_code.go":    []byte("package pkg\n// Code generated by x. DO NOT EDIT.\n"),
		"pkg/after_comment.go": []byte("\n// header\n// Code generated by x. DO NOT EDIT.\npackage pkg\n"),
		"pkg/block.go":         []byte("/*\n header\n*/\n// Code generated by x. DO NOT EDIT.\npackage pkg\n"),
		"pkg/code_block.go":    []byte("x := 1 /* comment\n*/\n// Code generated by x. DO NOT EDIT.\n"),
		"pkg/after_close.go":   []byte("/* c */ code\n// Code generated by x. DO NOT EDIT.\n"),
		"pkg/not_marker.go":    []byte("// Code generated by x. DO NOT EDIT. extra\npackage pkg\n"),
		"pkg/crlf.go":          []byte("// note\r\n// Code generated by x. DO NOT EDIT.\r\n"),
		"Gemfile.lock":         []byte("GEM\n"),
		"pkg/empty.go":         {},
		"pkg/nbsp.go":          []byte("\u00a0// comment\n世\n"),
	}
	root, _ := newRepoBytes(t, files)
	kept, dropped, _, err := Select(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	wantKept := []string{"fixtures/a.go", "pkg/after_close.go", "pkg/after_code.go", "pkg/code_block.go", "pkg/empty.go", "pkg/nbsp.go", "pkg/not_marker.go"}
	var got []string
	for _, f := range kept {
		got = append(got, f.Path)
	}
	if !reflect.DeepEqual(got, wantKept) {
		t.Fatalf("kept %v\ndropped %v", got, dropped)
	}
}

func TestClassifyLine(t *testing.T) {
	cases := []struct {
		line    string
		in      bool
		comment bool
		still   bool
	}{
		{"", false, true, false},
		{"   \t", false, true, false},
		{"// hi", false, true, false},
		{"  // hi", false, true, false},
		{"code // hi", false, false, false},
		{"/* c */", false, true, false},
		{"/* c", false, true, true},
		{"still", true, true, true},
		{"*/", true, true, false},
		{"*/ code", true, false, false},
		{"code /* c", false, false, true},
		{"a /* b */ c", false, false, false},
		{"/* a */ // tail", false, true, false},
		{"/*/", false, true, true},
		{"/**/", false, true, false},
		{"世", false, false, false},
	}
	for _, tc := range cases {
		comment, still := classifyLine(tc.line, tc.in)
		if comment != tc.comment || still != tc.still {
			t.Errorf("%q in=%v -> comment=%v still=%v, want %v %v", tc.line, tc.in, comment, still, tc.comment, tc.still)
		}
	}
}

func TestVendored(t *testing.T) {
	if !vendored("vendor/lib.go") || !vendored("a/node_modules/b.go") || !vendored("third_party/c.go") {
		t.Fatal("expected vendor segments")
	}
	if vendored("pkg/app.go") || vendored("notvendor/a.go") {
		t.Fatal("unexpected vendor")
	}
}

func TestSelectNotARepo(t *testing.T) {
	if _, _, _, err := Select(t.TempDir(), nil); err == nil {
		t.Fatal("expected error")
	}
}

func TestSelectNoCommit(t *testing.T) {
	root := t.TempDir()
	gitRun(t, root, "init", "-b", "main")
	if _, _, _, err := Select(root, nil); err == nil {
		t.Fatal("expected error")
	}
}

func TestSelectEmptyCommit(t *testing.T) {
	root := t.TempDir()
	gitRun(t, root, "init", "-b", "main")
	gitRun(t, root, "config", "user.email", "t@example.com")
	gitRun(t, root, "config", "user.name", "Test")
	gitRun(t, root, "commit", "--allow-empty", "-m", "empty")
	kept, dropped, commit, err := Select(root, nil)
	if err != nil {
		t.Fatal(err)
	}
	if commit == "" || len(kept) != 0 || len(dropped) != 0 {
		t.Fatalf("kept=%v dropped=%v commit=%q", kept, dropped, commit)
	}
}

func TestParseTree(t *testing.T) {
	in := []byte("\x00100644 blob abc\tfile.go\x00120000 blob def\tlink\x00160000 commit zzz\tsub\x00100644 blob hash\t\x00")
	paths, err := parseTree(in)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(paths, []treeBlob{{path: "file.go", id: "abc"}, {path: "link", id: "def"}}) {
		t.Fatalf("%v", paths)
	}
	if _, err := parseTree([]byte("no-tab\x00")); err == nil {
		t.Fatal("expected bad record")
	}
	if _, err := parseTree([]byte("only\tpath\x00")); err == nil {
		t.Fatal("expected bad meta")
	}
}

func TestParseBatch(t *testing.T) {
	body := []byte("hello")
	var buf bytes.Buffer
	buf.WriteString("abc blob 5\n")
	buf.Write(body)
	buf.WriteByte('\n')
	got, err := parseBatch(buf.Bytes(), []string{"a.go"})
	if err != nil || !bytes.Equal(got["a.go"], body) {
		t.Fatalf("%v %q", err, got["a.go"])
	}
	empty, err := parseBatch([]byte("abc blob 0\n\n"), []string{"e.go"})
	if err != nil || len(empty["e.go"]) != 0 {
		t.Fatalf("empty: %v %q", err, empty["e.go"])
	}
	if _, err := parseBatch(nil, []string{"a"}); err == nil {
		t.Fatal("short header")
	}
	if _, err := parseBatch([]byte("abc missing\n"), []string{"a"}); err == nil {
		t.Fatal("missing blob")
	}
	if _, err := parseBatch([]byte("abc blob zz\n"), []string{"a"}); err == nil {
		t.Fatal("bad size")
	}
	if _, err := parseBatch([]byte("abc blob 1\nXY"), []string{"a"}); err == nil {
		t.Fatal("missing newline")
	}
	if _, err := parseBatch([]byte("abc blob -1\n"), []string{"a"}); err == nil {
		t.Fatal("negative size")
	}
}

func TestReadBlobsErrors(t *testing.T) {
	boom := func(string, []string, []byte) ([]byte, error) {
		return nil, errors.New("git down")
	}
	if _, err := readBlobs(".", []treeBlob{{path: "a.go", id: "abc"}}, boom); err == nil {
		t.Fatal("git error")
	}
	if files, err := readBlobs(".", nil, boom); err != nil || len(files) != 0 {
		t.Fatalf("empty paths: %v %v", files, err)
	}
}

func TestRealGitCannotStart(t *testing.T) {
	prev := gitBin
	gitBin = "no-such-git-binary-xyz"
	t.Cleanup(func() { gitBin = prev })
	if _, err := realGit(t.TempDir(), []string{"rev-parse", "HEAD"}, nil); err == nil {
		t.Fatal("expected start failure")
	}
}

func TestSelectFromSubdir(t *testing.T) {
	root, commit := newRepoBytes(t, specFiles())
	sub := filepath.Join(root, "pkg")
	kept, _, got, err := Select(sub, nil)
	if err != nil {
		t.Fatal(err)
	}
	if got != commit || len(kept) != 2 {
		t.Fatalf("kept %d commit %s", len(kept), got)
	}
}

func TestSelectGitCommandErrors(t *testing.T) {
	git := func(_ string, args []string, _ []byte) ([]byte, error) {
		switch args[0] {
		case "rev-parse":
			if args[1] == "--show-toplevel" {
				return []byte("/repo\n"), nil
			}
			return []byte("abc\n"), nil
		case "ls-tree":
			return nil, errors.New("ls-tree")
		default:
			return nil, errors.New("unexpected")
		}
	}
	if _, _, _, err := Select("/repo", git); err == nil {
		t.Fatal("ls-tree")
	}
	git = func(_ string, args []string, _ []byte) ([]byte, error) {
		switch args[0] {
		case "rev-parse":
			if args[1] == "--show-toplevel" {
				return []byte("/repo\n"), nil
			}
			return []byte("abc\n"), nil
		case "ls-tree":
			return []byte("100644 blob abc\ta.go\x00"), nil
		default:
			return nil, errors.New("cat-file")
		}
	}
	if _, _, _, err := Select("/repo", git); err == nil {
		t.Fatal("cat-file")
	}
}

func TestSelectBadTree(t *testing.T) {
	git := func(_ string, args []string, _ []byte) ([]byte, error) {
		if args[0] == "rev-parse" && args[1] == "--show-toplevel" {
			return []byte("/repo\n"), nil
		}
		if args[0] == "rev-parse" {
			return []byte("abc\n"), nil
		}
		return []byte("no-tab\x00"), nil
	}
	if _, _, _, err := Select("/repo", git); err == nil {
		t.Fatal("expected bad tree")
	}
}

func TestKeepPathInvalidUTF8(t *testing.T) {
	if keepPath("pkg/a.go", []byte{0xff}) {
		t.Fatal("invalid utf-8 kept")
	}
	if !keepPath("pkg/a.go", []byte("package pkg\n")) {
		t.Fatal("code dropped")
	}
	if keepPath("README.md", []byte("hi\n")) {
		t.Fatal("docs kept")
	}
}

func TestIsGeneratedBareDoNotEdit(t *testing.T) {
	if isGenerated([]byte("DO NOT EDIT\n")) {
		t.Fatal("bare DO NOT EDIT matched")
	}
	if !isGenerated([]byte("// Code generated by x. DO NOT EDIT.\n")) {
		t.Fatal("marker did not match")
	}
	if isGenerated([]byte("package p\n")) {
		t.Fatal("plain code matched")
	}
}

func TestResolveTopTrims(t *testing.T) {
	root, _ := newRepoBytes(t, map[string][]byte{"a.go": []byte("package a\n")})
	top, err := resolveTop(root, realGit)
	if err != nil || top != root && !strings.HasPrefix(top, root) {
		// macOS may resolve /var -> /private/var; accept either the temp dir or its eval.
		if err != nil {
			t.Fatal(err)
		}
	}
	if top == "" {
		t.Fatal("empty top")
	}
	if _, err := os.Stat(filepath.Join(top, "a.go")); err != nil {
		t.Fatal(err)
	}
}
